spring:
  datasource:
    url: "jdbc:sqlserver://localhost:1433;database=ecommerce_db;encrypt=true;trustServerCertificate=true;"
    username: sa
    password: 123456
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    show-sql: true